#!/bin/bash
docker-compose down
if [ $(docker images -q --filter "reference=mern_app") ]; then
    echo "Container exists. Deleting it"
    docker rmi -f $(docker images -q --filter "reference=mern_app")
else
    echo "Image not found"
fi
sudo docker-compose up -d --build
